# Generated by Django 5.0.2 on 2025-06-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_department_head_of_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='phone number'),
        ),
    ]
